### ISSUE TITLE
Bots taking objectives way too slowly

### ISSUE THREAD

**Issue by ForeskinJohn** [ineedbots/iw4_bot_warfare#6]
I hate to spam here but ive noticed another issue with these dudes, they dont seem to be very aggressive in objective based modes, a good example of this is S&D, 9 rounds out of 10 they seem to just deathmatch, instead of sprinting to the objective with the bomb, another example is in domination, where it's way too easy to corner the opposite team, they seem to go for caps very slowly instead of sprinting and i feel like if they did there would be a lot more challenge here. they do the killing just fine, they just need to have a higher priority when it comes to objectives like flags and bombs. just a thought.

**Comment by ForeskinJohn** [comment]
I've also noticed that the waypoint on nuketown has bots gathering in numbers at doorways and at the semi truck, its not an original map so im not too concerned about it though.

**Comment by ineedbots** [comment]
In the case for the Nuketown pile up at the truck; if you crouch right against the ledge, you actually get stuck and can't mount it

![image](https://user-images.githubusercontent.com/751729/110541993-1fdbc380-80ee-11eb-96f2-b63fe3f2c439.png)

**Comment by ForeskinJohn** [comment]
Cool and thanks for clearing that up, and if I only add a few bots they
seem to be able to jump into the the trailer rather than piling on the
leader and getting trapped on a navmesh. Oh, and thanks for essentially
immortalizing the multiplayer games i grew up with, pezbots was just too
insane for me.

**Comment by ForeskinJohn** [comment]
will we see similar changes to the upcoming IW4x release coming to the T4M release?

**Comment by ForeskinJohn** [comment]
either way the changelog looks exciting!

**Comment by ineedbots** [comment]
all 4 versions of bot warfare get the same changes (when applicable)

**Comment by ForeskinJohn** [comment]
ive noticed in the past couple games that the bots are now unable to plant while playing s&d but i need to test some other maps before this becomes an issue, the bots looked as if they were trying to climb on some sort of ledge so it could just be a node conflicting with the objective.

**Comment by Boxhead78** [comment]
Indeed bots still should take objectives way more aggressively (version 2.0.2). If possible they also should move faster around the map generally.

**Comment by LeRutY** [comment]
+1 Also applies to Modern Warfare 3. I have increased the "Sprint" value to 100 (though they still don´t sprint as much as you would think). In objective based modes they really should take the most direct routes. A random or set number of bots can defend their own flag (in CTF). Sometimes Black Ops 1 and 2 bots suck too so if "Bot Warfare" can get it more consistently then it will be better than the bots made by Treyarch

**Comment by ineedbots** [comment]
fixed sprinting issue, problem was that the bots were not pressing the forward button when reaching a new waypoint,

as for the bot logic for playing the gametype, they play it just fine, but i guess the problem is that they have too much down time and are not agressively playing the objective as much as you want them too,
it must be those `wait( randomintrange( 3, 5 ) );` you see, maybe i'll try lowering the values and see

**Comment by LeRutY** [comment]
It looks like that "( 0, 2 )" are the minum values, if I change it to "( 0, 1 )" or "( 0, 0 )", I get "script runtime errors" and the match won´t start. But already with "0, 2" I´m noticing big changes in the AI´s aggression which is great. It´s like Black Ops AI behaviour now. So if "0, 2" is the lowest I can go for then it´s alright

The bots still don´t run all the time (of course I´m not talking about when they start to shoot at someone or something etc) but there´s an improvement nonetheless

**Comment by LeRutY** [comment]
It looks like that "( 0, 2 )" are the minimum values, if I change it to "( 0, 1 )" or "( 0, 0 )", I get "script runtime errors" and the match won´t start. But already with "0, 2" I´m noticing big changes in the AI´s aggression which is great. It´s like Black Ops AI behaviour now. So if "0, 2" is the lowest I can go for then it´s alright

The bots still don´t run all the time (of course I´m not talking about when they start to shoot at someone or something etc) but there´s an improvement nonetheless

**Comment by calldutychef** [comment]
I also noticed the problem in domination with nuketown map... The bots all respawn inside one house and are stuck at the doorway. Some bots should respawn in the garden at end of the map and use sometimes the corridor to go to objective B

**Comment by ForeskinJohn** [comment]
closing, this issue has long since been resolved now.
